### ISSUE TITLE
some part of PCL should probably depend on python-vtk and libvtk-java

### ISSUE THREAD

**Issue by trainman419** [ros-perception/perception_pcl#44]
When compiling against PCL without python-vtk installed, I get many warnings like:

```
-- The imported target "vtkPythonCore" references the file
   "/usr/lib/libvtkPythonCore.so.5.8.0"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/vtk-5.8/VTKTargets-release.cmake"
but not all the files it references.
```

Installing python-vtk fixes this.

I get similar warnings that are resolved by installing libvtk-java:

```
-- The imported target "vtkHybridJava" references the file
   "/usr/lib/jni/libvtkHybridJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/vtk-5.8/VTKTargets-release.cmake"
but not all the files it references.
```

**Comment by wjwwood** [comment]
I'm not sure this should be fixed here. I think PCL should depend on them.

**Comment by LucidOne** [comment]
@trainman419 did you open an issue on this against PCL?
Is PCL reasonably usable without these packages?

**Comment by trainman419** [comment]
I believe PCL is usable without this. I have not filed a bug upstream.

**Comment by LucidOne** [comment]
If PCL is usable without these packages, I am OK with perception_pcl depending on these packages.

This will probably get fixed in the next release.

**Comment by mikeferguson** [comment]
+1 to this getting fixed somewhere. If for some reason we aren't going to fix the dependencies, we should at least list this on the Indigo migration page, so people can easily figure out what to install to make their life in cmake not suck.

**Comment by DLu** [comment]
+1

**Comment by paulbovbel** [comment]
So the consensus is, there needs to be a build dependency on python-vtk and libvtk-java?

I will update the indigo branch sometime soon, if someone has this already setup on their machine, please feel free to submit a pull request.

**Comment by wjwwood** [comment]
@paulbovbel this is going to be an issue on Ubuntu xenial and perhaps wily (I haven't checked though).

Currently our rosdep rule for `python-vtk` resolves to `python-vtk` in xenial, but the `libpcl-dev` package in xenial depends on `libvtk6-dev` (http://packages.ubuntu.com/xenial/libpcl-dev) which in turn depends on `python-vtk6` (http://packages.ubuntu.com/xenial/libvtk6-dev). This causes a loop where every time you run `rosdep install ...` it will uninstall `python-vtk` and then install `python-vtk6` and then the next time you run it will do the opposite.

I think we should probably create a Kinetic branch for this package and remove the dependency on explicit dependency on `python-vtk` since `libpcl-dev` appears to have it now.

**Comment by tfoote** [comment]
@wjwwood that will only solve it for this package. Any package that asks for python-vtk and libpcl-dev will run into this problem. We should probably consider changing to python-vtk6 to be compatible. What is the level of API change between plain and version 6?

**Comment by wjwwood** [comment]
@tfoote based on this thread, the dependency was introduced here just because it was missing in the pcl binary, which no longer seems to be the case. So we could remove the dependency here, remove the wily and xenial entries for the key and recommend anyone else who tries to use to instead move to a new key called `python-vtk6` which can be created as needed.

**Comment by tfoote** [comment]
I created a ticket to track this in an open state https://github.com/ros/rosdistro/issues/10752 lets move the discussion there.

**Comment by paulbovbel** [comment]
@wjwwood thanks, removing python-vtk for kinetic-devel
