### ISSUE TITLE
release hydro pcl_ros

### ISSUE THREAD

**Issue by garaemon** [ros-perception/perception_pcl#61]
Could you release the latest hydro-devel branch of pcl_ros?

It includes a lot of nodelets.
https://github.com/ros-perception/perception_pcl/commit/def6bae2160854ff662b222ed9500c0c39e32071

**Comment by paulbovbel** [comment]
Done!

**Comment by martimorta** [comment]
Thanks, I was going to ask for the same.

I would like to know, is the releasing requested manually? In every ROS package?
Thanks in advance!

**Comment by paulbovbel** [comment]
Package release is a manually-triggered process, but you don't really need to request it, I'm just a little out of touch with ROS duties due to thesising and work.

Even after I release, it takes a while to get synced from the shadow-fixed into the public debs (another manually-triggered process done by the osrf), so you won't see the changes in the public packages for a while.
