### ISSUE TITLE
why class_loader_hide_library_symbols is needed?

### ISSUE THREAD

**Issue by k-okada** [ros-perception/perception_pcl#9]
Hi,

We're developing pcl::FIlter based PCL nodelet library at http://svn.code.sf.net/p/jsk-ros-pkg/code/trunk/jsk_pcl_ros, but it does not work since groovy. 
Some of our code uses  pcl_ros::Filter as a super class, for example resize_points_publisher.cpp, but it fails to load as following message.

However, the code works, if we remove 
    class_loader_hide_library_symbols(pcl_ros_filters)
from CMakeLists.txt,

So, why class_loader_hide_library_symbols is needed? if it is not important, is it possible to remove this line from CMakeLists.txt?

[ERROR] [1367521319.699211347]: Failed to load nodelet [/depth_image_creator_nodelet] of type [jsk_pcl/DepthImageCreator]: Failed to load library /home/k-okada/ros/groovy/jsk-ros-pkg/jsk_pcl_ros/lib/libjsk_pcl_ros.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/k-okada/ros/groovy/jsk-ros-pkg/jsk_pcl_ros/lib/libjsk_pcl_ros.so: undefined symbol: _ZN7pcl_ros6Filter15config_callbackERNS_12FilterConfigEj)
[FATAL] [1367521319.699405536]: Service call failed!

**Comment by tfoote** [comment]
@mirzashah can answer more fully.  

But at the high level.  You cannot depend on symbols in other plugins due to them being dynamically loaded, and potentially unloaded while you're running.  Even worse is if you get linked against other plugins you can no longer unload correctly.  

PS for questions answers.ros.org is more appropriate.
